// eslint-disable-next-line @typescript-eslint/no-unused-vars
import * as _ from "electron";

export const {
  BrowserView,
  BrowserWindow,
  Menu,
  MenuItem,
  MessageChannelMain,
  Notification,
  ShareMenu,
  TouchBar,
  Tray,
  app,
  autoUpdater,
  clipboard,
  contentTracing,
  crashReporter,
  desktopCapturer,
  dialog,
  getCurrentWebContents,
  getCurrentWindow,
  getGlobal,
  globalShortcut,
  inAppPurchase,
  ipcMain,
  nativeImage,
  nativeTheme,
  net,
  netLog,
  powerMonitor,
  powerSaveBlocker,
  process,
  protocol,
  // require,
  screen,
  session,
  shell,
  systemPreferences,
  webContents,
  webFrameMain,
} = window.require("@electron/remote");
